### ISSUE TITLE
Data not found error .. #helpwanted

### ISSUE THREAD

**Issue by sathishgkk** [KishanViramgama/WhatsApp-Status-Download#2]
[
[Document1.docx](https://github.com/KishanViramgama/WhatsApp-Status-Download/files/6737645/Document1.docx)
]

NO DATA FOUND error in both mobile and android emulator ,please help me to resolve the issue
where to give the whatsapp status direectory location??

**Comment by KishanViramgama** [comment]
First of all view status in whatsapp app then after open this app @sathishgkk
