### ISSUE TITLE
admob interstitial ads not support in any activity

### ISSUE THREAD

**Issue by vkrstickers** [KishanViramgama/WhatsApp-Status-Download#3]
i have try to implement in main activity and other fragment but interstitial ad not support ... i have import the interstitial but this invisible in within a second

**Comment by KishanViramgama** [comment]
Implement  proper way

**Comment by wilsoncaty** [comment]
Hi sir, iam try your app but not working in android R

**Comment by KishanViramgama** [comment]
right now `targetSdkVersion 30` not supported this project. I am update after some time @YASIRAG

**Comment by wilsoncaty** [comment]
> right now `targetSdkVersion 30` not supported this project. I am update after some time @YASIRAG

okay sir...we stay for new update
